name: Terraform CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:

  terraform-validation:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4


      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.13.0'


      # 3. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./module


      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./module


      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./module


      # 6. Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest


      # 7. TFLint
      - name: Run TFLint
        run: |
          tflint --init
          tflint --minimum-failure-severity=error
        working-directory: ./module


      # 8. Checkov Security Scan
      - name: Checkov Terraform Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./module
          framework: terraform
          soft_fail: false


      # 9. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan
        working-directory: ./module


      # 10. Upload Terraform Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./module/tfplan
